### ISSUE TITLE
DCACHE_FALLTHRU 플래그의 의미

### ISSUE THREAD

**Issue by chanyoung** [HCLS/linux-4.11#11]

**Comment by fennecis** [comment]
일단 알아 본 내용까지만 정리하겠습니다.

**layered filesystem**과 연관이 있는 것 같습니다.
layered filesystem은, 한 파일시스템의 하위 디렉토리에 또 다른 파일시스템을 마운트해도 두 파일시스템의 파일 모두 정상적으로 사용가능하도록 해주는 것으로, union filesystem과 유사한 개념으로 알고 있습니다..

**DCACHE_FALLTHRU**가 설정되어 있는 덴트리는 그의 상위 파일시스템에서 **visible**하며, 접근 가능한 덴트리를 의미합니다.
연관된 플래그로, **DCACHE_WHITEOUT** 플래그가 있습니다. 이는 DCACHE_FALLTHRU와 반대로 그의 상위 파일시스템에서 접근 불가하도록 **hiding** 하고자 할 경우 설정합니다.


(layered filesystem에 대한 더 자세한 공부가 필요함.)
