### ISSUE TITLE
함수명이 trace_* 인 커널 함수들의 의미

### ISSUE THREAD

**Issue by melody1214** [HCLS/linux-4.11#13]
관련 소스코드

include/trace/events/writeback.h

참고자료

https://burzalodowa.wordpress.com/2013/07/09/linux-kernel-tracing/
http://elixir.free-electrons.com/linux/latest/source/include/trace/define_trace.h#L25

**Comment by fennecis** [comment]
tracepoint는 커널 분석을 위해 사용하는 추적점으로, 특정 커널 코드 위치에 데이터를 저장합니다. TRACE_EVENT() 매크로가 등장한 것이 바로 이 tracepoint의 콜백 생성을 자동화하기 위함입니다.

개발자가 TRACE_EVENT() 매크로를 이용하여 tracepoint들을 서브시스템에 추가하면, 그 tracepoint들을 Ftrace가 자동으로 추적할 수 있게 됩니다. 개발자는 Ftrace의 동작방식을 몰라도 됩니다. 

아래는 TRACE_EVENT() 매크로의 파라미터 설명입니다.


TRACE_EVENT(name, proto, args, struct, assign, print)

· name         - 생성될 tracepoint의 이름. 
· prototype  - 콜백함수의 프로토타입. 
· args           - 프로토타입의 인자들.
· struct         - tracer의 링 버퍼에 저장 될 데이터의 구조.
· assign        - 데이터를 구조체에 할당하는 방식 (파라미터의 데이터가 링 버퍼에 저장되는 방식).
· print          - ASCII 형식으로 구조체를 출력할 방식.


아래 링크에서 자세하게 설명하고 있습니다.
https://lwn.net/Articles/379903/
