### ISSUE TITLE
shrink_dcache_parent()의 quadratic behavior는 무엇을 말하는 것인가

### ISSUE THREAD

**Issue by chanyoung** [HCLS/linux-4.11#16]
fs/dcache.c: shrink_dentry_list() 함수안에 주석으로 나와있다.

**Comment by ahjea** [comment]
참고링크 : http://lkml.iu.edu/hypermail/linux/kernel/0702.1/0668.html

리눅스 패치에 대한 코멘트이고 일단 다른함수에서 쓰였지만 과정이 유사하고
shrink_dentry_list에서 발견한 quadratic behavior에서도 같은 의미로 쓰였기 때문에 참조링크로 달아둡니다.

이 링크의 내용에 따르면 shrink_dcache_parent 함수는 일단 무한루프를 사용하고 여러번 수행될경우 
큰 오버헤드를 가지는, 커널입장에서는 아주 못된 함수 입니다. 
트리가 생성될때 depth에 대해  quadratic, 즉 지수배의 operation을 만들어 낼수 있다고 합니다.
위 패치는 이런 함수를 호출해서 반복해서 실행시키는것보다 d_invalidate라는 함수를 통해 
사용되지않는 dentry의 서브트리를 통째로 떼어버려주는 함수를 만들어 
이런 오버헤드를 줄이도록 패치를 했다는 내용의 링크입니다.

이런 패치의 방향에 맞춰 코드를 살펴보게되면

이 d_invalidate 함수를 살펴보면 지울 테이터를 찾게되면 shrink_dentry_list 함수를 호출합니다.
(이 데이터의 경우 구조체로 umount지점, 삭제를 시작할 덴트리 트리 시작지점과 몇개를 지워야하는지등
삭제에 필요한 데이터들이 담겨져 있습니다.)

이렇게 호출이 된 shrink_dentry_list는 삭제를 시작할 지점과 어디까지 삭제해야하는지 등의 정보를 모두 가진채로 호출이 된 상태입니다.  여기까지는 저희가 의문을 가지기 전 루틴까지 실행하게 되면
이 패치에서 말한대로 서브트리를 떼어낸 후 그 서브트리를 하나하나 해제해 주는 작업이 끝나게 됩니다.
이후 저희가 의문을 가진 주석과 함께 while문이 나오게 되는데 지금 주석을 보시면 이해가 되실것입니다.

의문을 가진 주석은 아래와 같습니다.
We need to prune ancestors too. This is necessary to prevent quadratic behavior of shrink_dcache_parent, but is also expected to be beneficial in reducing dentry cache fragmentation

해석해 보자면
shrink_dcache_parent에서 나올 수 있는 지수배의 가지수는 반드시 막아야될 일이었고 그렇기 때문에 
선조들을 지우는것은 필요한 일이었다 
=> 여기까지는 왜 shrink_dentry_list가 생겼고 d_invalidate에 의해 호출되었는지 참조 페이지에 나온 내용 그대로 입니다.

여기서부터가 중요합니다.
추가적으로 dentry cache의 단편화(그러니까 필요없는것은 최대한 쳐내야 한다는것입니다.)가 이뤄진다면 더 나은 기대효과(이익)을 얻을 수 있기때문에 아래 루틴이 존재한다. 
아래 while루틴이 또 추가로 실행되게 된다 정도로 해석할 수 있겠습니다.

Conclusion)
shrink_dcache_parent함수는 한번한번 부르기엔 오버헤드가 많다.
그래서 d_invalidate함수를 통해 매크로처럼 트리를 통째로 띄어버리는 작업을 만들었다.
하지만 정해진것만 지우는것보다 추가적으로 지울부분이 더 있다면 최대한 찾아서 지우는것이
단편화를 막아주고 더 간단한 트리를 만들어주게된다.
그래서  shrink_dentry_list()에 while문으로 한번더 검사를해주고 삭제를 해준다.

P.S. 해석할떄 좀 더 원활한 이해를 돕기위해 의역을 조금 했는데 바로 안와닿을수 습니다. 
       의미상으로 저렇게 해석하여도 문제가 없다고 생각하여 저렇게 해석을 해 놓았습니다.
