### ISSUE TITLE
cpu_relax() 추가 설명 필요

### ISSUE THREAD

**Issue by chanyoung** [HCLS/linux-4.11#17]
fs/dcache.c: shrink_dentry_list 에서 사용됨.

**Comment by melody1214** [comment]
cpu_relax()는 시간 지연에 쓰이는 매크로 함수로 CPU에 휴식에 대한 힌트를 준다.

`#define cpu_relax() asm volatile("rep; nop")`
위와 같이 정의(Intel 기준)되어 있으며, nop(no operation)을 rep(repeat)하는 명령이다.
pause() 명령과 동일한 동작을 한다.

예제 코드를 보면,

```
unsigned long delay = jiffies + 10 * HZ;
while (time_before(jiffies, delay))
    cpu_relax();
```

위 코드는 delay 동안 루프를 돌며 busy waiting을 하는데, 이 때 CPU에 미리 힌트를 준다.
CPU에 이 부분이 spin-wait loop라고 알려줌으로써 전력 소모를 줄인다.
커널에서 흔히 쓰이는 spinlock이 이 함수를 이용하여 구현되어있다.

```
unsigned long delay = jiffies + 10 * HZ;
while (time_before(jiffies, delay));
```

위 코드는 cpu_relax() 함수만 빠진 형태로 CPU 전력 소모가 높다.

ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ

1. 힌트를 주고, 전력 소모를 줄이는 자세한 동작에 대해 알아볼 필요가 있음
