### ISSUE TITLE
RCU read-side critical section 은 어떻게 정의되는가? 

### ISSUE THREAD

**Issue by chanyoung** [HCLS/linux-4.11#2]
fs/dcache.c: lock_parent() 함수에서 rcu_read_lock()을 호출한다. 하지만 락의 객체가 없이 호출된다. RCU read-side critical section이 어떻게 정의되는지, 혹은 RCU protected data가 어떻게 정의되는지 궁금하다.

**Comment by chanyoung** [comment]
## dcache와 RCU

각자 PC에서 $slabtop 명령어를 쳐보면 알 수 있듯이, dentry 정보는 슬랩 할당자를 통해 슬랩으로 할당되며 캐싱된다.

![image](https://cloud.githubusercontent.com/assets/6683987/26086542/3d9c9358-3a26-11e7-84ff-5aa5204a8f91.png)


커널은 dcache_init() 함수에서 덴트리 캐싱을 위한 kmem_cache 구조체를 생성하고, 커널의 cache_chain에 추가한다(KMEM_CACHE(dentry, ...) -> kmem_cache_create() ). 그리고 캐싱된 덴트리를 효율적으로 접근하기 위해 해시테이블(dentry_hashtable)을 생성하여 사용한다. 이를 위해서 덴트리 구조체에는 해시테이블의 각 해시 리스트에 연결되는 "struct hlist_bl_node d_hash" 멤버가 있다.

각 해시 리스트는 RCU로 보호되며, 따라서 리스트 walking 작업은 리스트 업데이트(삽입, 삭제) 동작과 병렬적으로 수행이 가능하다.

**RCU는 잠금을 하지 않으면서 동기화를 이루기 위한 커널 API**이다. 잠금을 하지 않기 때문에 누군가 읽고있는 데이터도 동시에 수정이 가능하다. VFS의 덴트리는 RCU로 보호되는 대표적인 자원이며, RCU를 적용하고 lookup 과정이 덴트리 리스트의 업데이트 동작과 병렬적으로 수행가능해져 성능향상을 가져온 대표적 케이스다.

예를 들어, 한빛 미디어의 "리눅스 커널 락을 없애려는 시도들"에서 RCU를 설명하는 부분을 살짝 바꿔서 설명을 해보자면,

> CPU0이 A라는 덴트리를 접근하고 있고, CPU1이 A를 접근해서 덴트리를 수정해버리면 RCU에서는 A"을 생성한다. 이때는 시스템에 A와 A"이 동시에 존재하게 된다. 이때 CPU2가 A를 접근하게 되면 RCU에 등록된 연결리스트를 타고 A"에 접근하게 된다. 시간이 경과해서 CPU0이 A라는 덴트리를 더 이상 접근하지 않게 되면 RCU에서는 A를 완전히 제거하게 된다.

```
+-------+
|   d   |
|   e   |       +---------+        +--------+        +--------+
|   n   |  -->  |    /    |  --->  |   A"   |  --->  |   B    |  --->
|   t   |  <--  |         |  <---  |        |  <---  |        |  <---   ...
|   r   |       +---------+        +--------+        +--------+
|   y   |             ^                                  ^
|   -   |             |           +---------+            |
|   h   |             +--------   |    A    | -----------+
|   a   |                         +---------+
|   s   |
|   h   |
|   t   |    ---->
|   a   |   <----         ....
|   b   |
|   l   |    ----->
|   e   |   <-----        ....
+-------+
```

RCU로 보호를 받는 자원은 리스트나 트리 형식으로 관리된다. 하지만 이를 위한 별도의 커널 리스트나 트리 자료구조가 존재하는 것은 아니다. **RCU로 보호를 받는 자원은 커널에서 제공하는 일반적인 list, hlist, hlist_bl 등의 자료구조를 이용하여 관리하되, 각 리스트에 접근할 때 RCU API를 이용하여 접근하는 방식을 사용**한다. (hlist_bl_add_head_rcu(), hlist_bl_del_rcu(), hlist_bl_for_each_entry_rcu() 등등..)

또한, RCU로 보호를 받는 자원(예를들어 덴트리 구조체)은 다른 잠금 기법처럼 참조카운트를 관리하는 멤버 변수를 갖지 않는다. 따라서 직접 자원의 참조 카운팅을 관리하는 코드를 작성하지 않아도 되고, 커널의 RCU API를 이용하여 접근하기만 하면 된다. 또한, 덴트리 구조체 멤버의 수정이 일어나지 않기 때문에, CPU cache invalidation이 발생하지 않아 효율적인 walking 작업을 할 수 있다. (rcu walk)

dcache.c에서 덴트리 리스트에 RCU API를 통해 접근하는 사례를 간단하게 정리하면 아래와 같다.
dentry_free() {
  ...
  call_rcu()
  ...
}

d_alloc_parallel() {
  ...
  rcu_read_lock()
  ...
  hlist_bl_add_head_rcu()
  ...
  rcu_read_unlock()
}

__d_lookup_rcu() {
...
hlist_bl_for_each_entry_rcu()
...
}

이 외에 많은 접근 과정에서 아래 과정을 통해 rcu read-side 크리티컬 섹션을 정의하고 보호를 받는다.
...
rcu_read_lock()
...
rcu_read_unlock()
...

정리하자면, 
덴트리는 해시 리스트로 관리되며 이 리스트는 RCU API로 접근한다. 다시말하면 덴트리와 그 해시 리스트는 RCU로 보호받는다. 읽기 작업을 하는 경우 rcu_read_lock의 보호 아래 작업중인 덴트리가 삭제/변경될 걱정 없이 일을 수행할 수 있다. 덴트리를 해시 리스트에 추가, 제거, 탐색하는 경우 커널 RCU API로 접근하여 다른 작업과 충돌없이 병렬적으로 작업을 수행한다.

(관련 커널 문서 및 기사, 읽어보시길)

[[What is RCU]](http://elixir.free-electrons.com/linux/v4.11/source/Documentation/RCU/whatisRCU.txt)                   
[[Filesystem path lookup]](http://elixir.free-electrons.com/linux/v4.11/source/Documentation/filesystems/path-lookup.txt)    
[[Scaling dcache with RCU]](http://www.linuxjournal.com/article/7124?page=0,0) 


_P.S. RCU 내부 구현과 작동 원리는 파일시스템 스터디가 끝난 후 진행하면 좋을 것 같습니다._

**Comment by ahjea** [comment]
hi

**Comment by chanyoung** [comment]
## call_rcu()

지난번에 나온 call_rcu() 관련 커널 문서를 읽어보았습니다.
주절주절 말들이 좀 있긴 하지만 핵심은 이 한줄이네요.
_**"call_rcu()는 블록킹 대신 RCU read-side critical section이 끝나면 수행될 콜백 함수들을 등록한다."**_

**Comment by chanyoung** [comment]
덴트리 해시 리스트에서 삭제하는 d_drop() 루틴을 보면, RCU API를 통해 해시 리스트에서 제거하지 않는다.

이에 관한 확인이 필요하다.

**Comment by chanyoung** [comment]
RCU API 중 리스트 삭제 함수들을 살펴보았습니다.
예로 지금 이슈가 된 **_hlist_bl_del_** 과 **_hlist_bl_del_rcu_** 를 보면 아래와 같습니다.

```
static inline void hlist_bl_del(struct hlist_bl_node *n)
{
    __hlist_bl_del(n);
    n->next = LIST_POISON1;
    n->pprev = LIST_POISON2;
}

vs

static inline void hlist_bl_del_rcu(struct hlist_bl_node *n)
{
    __hlist_bl_del(n);
    n->pprev = LIST_POISON2;
}
```

리스트 삭제 함수는 RCU API나 그냥 리스트 삭제 함수나 큰 차이가 없었습니다. (왜 차이가 없는지는 추후에 커널 동기화 기법에 대해 더 공부한 후 알아보면 좋을 것 같네요.)
다만 다른점 중 하나는 코드의 주석을 보면, 리스트에서 제거 후 바로 객체를 메모리에서 해제하지 말고 **_synchronized_rcu_** 나 **_call_rcu_** 를 호출하여 메모리 해제를 하라는 것입니다. 

그리고 지금 이슈가 된 **___d_drop_** 함수에서 덴트리 해시 리스트로부터 삭제하는 코드를 보면 이렇습니다.

```
void __d_drop(struct dentry *dentry) 
{
    ....
    __hlist_bl_del(&dentry->d_hash);
    dentry->d_hash.pprev = NULL;
    ....
}
```

**_hlist_bl_del_rcu_** 와 비교하면 **_dentry->d_hash.pprev_** 를 **_LIST_POISON2_** 대신 **_NULL_** 로 만들어준다는 것 밖에 다른점이 없습니다. **_LIST_POISON_** 이 어떤 이점을 가져다 주는지는 더 공부를 해보아야 알겠지만, 사실 리스트 삭제 후 가지고 있던 포인터를 **_NULL_** 로 만들어주는게 가장 일반적인 동작임을 생각해보면 **___d_drop_** 함수에서 해시 리스트에서 제거하는 방법은 **_hlist_bl_del_rcu_** 와 비교하여 보았을 때 이상하지 않습니다.

그리고 **___d_drop_** 에서 해시 리스트로부터 제거한 다음 **_dentry_free_** 함수에서 덴트리 객체를 해제하게 되죠. 이 때 **_call_rcu_** 를 호출하여 RCU read-side critical section이 끝나면 메모리에서 안전하게 해제하게끔 합니다.

```
static void dentry_free(struct dentry *dentry)
{
    ...
    call_rcu(&dentry->d_u.d_rcu, __d_free);
}
```

이를 보았을 때, 지금 덴트리를 해시 리스트에서 제거하고 메모리에서 해제하는 루틴은 RCU 보호를 잘 지켜주고 있다고 볼 수 있습니다.

다만 RCU로 보호받는 자료구조에서 삭제 작업이 일어날 때 어떤식으로 동작하는지는 한번 더 확인해봄이 좋을 것 같네요.
