### ISSUE TITLE
open시 inode 관련

### ISSUE THREAD

**Issue by ahjea** [HCLS/linux-4.11#24]
1. 아이노드가 공유되며 아이노드가 시스템화이드하게 1개만 존재하는지

2. 공유되고 한개인게 맞다면 오픈시 이미 존재하는 아이노드에 대해 어떻게 처리가 되는지

**Comment by yoonsue** [comment]
https://notes.shichao.io/apue/ch3/#chapter-3-file-io
![image](https://user-images.githubusercontent.com/22068030/48591956-9dadbb00-e989-11e8-87ae-ea0fdce7a54c.png)

+) dup 
![image](https://user-images.githubusercontent.com/22068030/48591967-a69e8c80-e989-11e8-9927-ee75255332cc.png)
