### ISSUE TITLE
spin_lock_nested()의 역할은 무엇인가

### ISSUE THREAD

**Issue by chanyoung** [HCLS/linux-4.11#3]
fs/dcache.c: lock_parent()

**Comment by ahjea** [comment]
먼저 기본적으로 nested lock이라 함은 a1과 a2라는 객체가 존재할때, 
a1 -> a2 순서로 락이 걸렸으면 푸는 순서는 a2 -> a1 이런 순서가 되어야 한다는 것이다.
이를 지키지 않으면 락이 풀리지 않는다. 

```
/*
 * Remove the lock to the list of currently held locks - this gets
 * called on mutex_unlock()/spin_unlock*() (or on a failed
 * mutex_lock_interruptible()).
 *
 * @nested is an hysterical artifact, needs a tree wide cleanup.
 */
static int
__lock_release(struct lockdep_map *lock, int nested, unsigned long ip)
```
=> 코드가 길기때문에 커널에있는 주석과 함수이름만 적어았습니다.

이런식으로 nested 플래그가 unlock 함수에 들어가게 되고 이 함수를 보게되면 lock의 depth역시 고려해서 해제가 이루어지는듯 하다.

기본적으로 이 nested를 사용하는 이유는 락의 중첩사용에서 발생하는 데드락의 위험성이 있을경우 사용하는것이 대부분이다. 이 dcach.c에서는 locking 알고리즘이 조금 특이하게 작용을 하는데 함수를 보면 아래와 같다.

static inline struct dentry *lock_parent(struct dentry *dentry)
{
	struct dentry *parent = dentry->d_parent;

	if (IS_ROOT(dentry))

		return NULL;

	if (unlikely(dentry->d_lockref.count < 0))

		return NULL;

	if (likely(spin_trylock(&parent->d_lock)))

		return parent;

	rcu_read_lock();

	spin_unlock(&dentry->d_lock);

again:

	parent = ACCESS_ONCE(dentry->d_parent);

	spin_lock(&parent->d_lock);

	/*

	 * We can't blindly lock dentry until we are sure

	 * that we won't violate the locking order.

	 * Any changes of dentry->d_parent must have

	 * been done with parent->d_lock held, so

	 * spin_lock() above is enough of a barrier

	 * for checking if it's still our child.

	 */

	if (unlikely(parent != dentry->d_parent)) {

		spin_unlock(&parent->d_lock);

		goto again;

	}

	rcu_read_unlock();

	if (parent != dentry)

		spin_lock_nested(&dentry->d_lock, DENTRY_D_LOCK_NESTED);

	else

		parent = NULL;

	return parent;

}

함수를 보면 부모에 대해서 trylock을 시도하면 바로 리턴이 되는것을 알 수 있다. 이 때 락의 중첩된 모습은  child락이 걸린상태에서 parent락이 걸린 상태로 볼 수 있다. 하지만 trylock이 실패하게되면 조금 다른 양상을 보이게 된다.  rcu_read_lock이 걸리면서 걸려있던 child락이 풀리게 된다. 그러면서 메모리에 존재하는 parent를 읽어와서 락을 child보다 먼저걸게 된다. parent에 대한 locking이 끝나게 되면 rcu에 걸려있던 락을 풀고 nested락을 걸게 된다. 

이것저것 찾아보면서 이런 흐름에 대해 다시한번 생각을 해 보았는데 child->parent 순으로 락이 걸리는 경우 deadlock 발생확률이 없는 것으로 생각이 된다. shrink_dentry_list 함수를 보면 모두 락을 해제할때 child 락을 해제한 후 parent락을 해제하는것을 볼 수 있다. 아무래도 child의 경우 루틴에 따라 실행되다보면 parent의 락을 잡은 경우가 발생하기 때문에 이런 장치를 해놓은것 같고 이런 경우는 shrink_dentry_list에 대해 스터디가 끝나고 VFS에 대해 좀더 이해가 높아지면 알 수 있을 것으로 생각된다. 

찾아보면서 유용하다고 생각했던 참조 링크
http://stackoverflow.com/questions/12013089/when-would-you-ever-use-nested-locking
