### ISSUE TITLE
덴트리 구조체 안에 d_lockref.count 가 음수일 때 의미

### ISSUE THREAD

**Issue by chanyoung** [HCLS/linux-4.11#4]
fs/dcache.c: lock_parent() 함수 내에 있음.

**Comment by melody1214** [comment]
http://linux-fsdevel.vger.kernel.narkive.com/AfFTqyNU/adding-concept-of-dead-references-to-lockref

**Comment by melody1214** [comment]
__dentry_kill(struct dentry *dentry) 함수 내부에서 lockref_mark_dead(&dentry->d_lockref)를 호출하고,
lockref_mark_dead() 함수에서는 refcount의 값을 -128로 설정한다.
이 값은 dentry가 현재 'unrecoverably dead' 상태라는 것을 의미한다.
