### ISSUE TITLE
this_cpu_dec(nr_dentry_unused) 의 역할

### ISSUE THREAD

**Issue by chanyoung** [HCLS/linux-4.11#5]
fs/dcache.c: d_shrink_del()

덴트리를 리스트에서 삭제한 후 이 코드를 동작시킨다.

**Comment by melody1214** [comment]
각 cpu마다 nr_dentry (dentry 갯수), nr_dentry_unused (미사용 dentry, 즉 LRU 갯수) 를 관리한다.
d_shrink_del() 함수에서 dentry의 LRU를 리스트에서 삭제한 후 this_cpu_dec(nr_dentry_unused)를 호출한다.
LRU 삭제 후 현재 cpu에 저장되어 있는 LRU 갯수를 줄이기 위해 this_cpu_dec(nr_dentry_unused)를 사용한다.
반대로 LRU를 추가할 때에는 this_cpu_inc()를 사용한다.

**Comment by wonjiwoong** [comment]
dfdf
