### ISSUE TITLE
덴트리 구조체에 d_u.d_alias 의미

### ISSUE THREAD

**Issue by chanyoung** [HCLS/linux-4.11#6]
fs/dcache.c: dentry_free() 함수에서 사용됨

```
WARN_ON(!hlist_unhashed(&dentry->d_u.d_alias));
```

**Comment by chanyoung** [comment]
## d_alias
d_alias는 덴트리 구조체가 연결되어 있는 리스트 중 하나로, 정의는 이렇습니다.

> 같은 아이노드를 가르키는 덴트리 리스트

쉽게 생각하고자 하면 하드 링크를 생각해보면 될 것 같아요.

그럼 더 자세히 알아보도록 하겠습니다.  
d_alias는 타입이 hlist_node 입니다. hlist는 해시 리스트를 의미하구요. 커널 자료구조에서 해시 리스트는 아래와 같은 구조를 갖습니다.

```
+-------------+
|  hlist_head | ---> hlist_node ---> hlist_node ---> hlist_node
|    first    | <---            <---            <---
+-------------+
|             |
+-------------+
|             |
+-------------+
|             |
+-------------+
```

d_alias는 hlist_node이기 때문에, 해시테이블의 엘리먼트인 어떤 hlist_head의 first에 연결되어야 합니다. 그러면 d_alias들이 매달리는 hlist_head는 누가 갖고있을까요? d_alias는 같은 아이노드를 갖는 덴트리들의 리스트라고 정의했었습니다. 그렇다면 hlist_head를 갖기 가장 적합한 자료구조는 아이노드가 되겠지요. 따라서 아이노드는 i_dentry라는 필드를 가지고 있고, 이 필드의 타입은 hlist_head가 됩니다. 그리고 필요에 따라서 아이노드에서 덴트리로 역참조가 가능하게 됩니다.

```
struct inode {
...(생략)
    union {
        struct hlist_head i_dentry
        ...(생략)
    }
...(생략)
}
```

충분히 이해하셨다면, 아래 영문으로 된 d_alias에 대한 설명을 읽어보시기 바랍니다.

> A circularly linked list with one special element, we here have a circularly linked list passing through the d_alias field of all dentries that are aliases of one inode, and through the i_dentry field of the inode.

_special element_ 는 아이노드의 _i_dentry_ 를 의미하는 것이고, _special element_ 에 _d_alias_ 를 이용하여 원형 리스트로 연결되어 있다는 뜻이 되겠습니다.

**Comment by melody1214** [comment]
확인완료했습니다.
