### ISSUE TITLE
DCACHE_DENTRY_CURSOR 의 의미

### ISSUE THREAD

**Issue by chanyoung** [HCLS/linux-4.11#9]
fs/dcache.c: dentry_unlist() 함수에서 사용됨.

해당 플래그가 세팅된 경우 무슨 의미인지 파악 필요

**Comment by melody1214** [comment]
이 플래그는 우선 ramfs, debugfs 등 몇개의 파일 시스템에서만 사용되며,
디렉토리 파일 open 시

1. `dcache_dir_open(inode, file);`
2. `d_alloc_cursor(file->f_path.dentry);`
3. `__d_alloc(parent->d_sb, NULL);`

위 순서대로 동작 후 __d_alloc의 return value로 dentry를 받으면,
해당 dentry의 플래그에 **DCACHE_RCUACCESS**, **DCACHE_DENTRY_CURSOR**를 추가로 set 한다.

정확한 의미를 파악하고 동작을 분석하기 위해서는 ramfs와 같은 파일시스템 코드 중
디렉토리 파일을 open하는 경우를 분석해봐야 할 것 같다.

ramfs_mkdir, ramfs_symlink 등에서 사용되는 것은 확인이 되었으나 좀 더 분석이 필요하다.
